fake_pole_detection_node:
 ros__parameters:
  radius_detection: 35
  min_noise_error_sigma: 0.1
  max_noise_error_sigma: 0.6
main_node:
 ros__parameters:
  use_landmark_assignment_algorithm: True
  gps_noise_error_sigma: 0.5